from typing import Protocol
from uuid import UUID

from domain.models.role import RoleCreate, RoleUpdate


class RoleRepository(Protocol):
    async def list_roles(self): ...

    async def create_role(self, data: RoleCreate): ...

    async def get_role_by_id(self, role_id: UUID): ...

    async def get_role_by_name(self, name: str): ...

    async def update_role(self, role_id: UUID, data: RoleUpdate): ...

    async def delete_role(self, role_id: UUID): ...

    async def assign_role(self, user_id: UUID, role_name: str): ...

    async def revoke_role(self, user_id: UUID, role_name: str): ...

    async def get_user_roles(self, user_id: UUID) -> list[str]: ...
