from typing import Protocol
from uuid import UUID

from domain.models.user import UserCreate


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID): ...

    async def get_by_login(self, login: str): ...

    async def create_user(self, data: UserCreate, *, password_hash: str): ...

    async def set_login(self, user_id: UUID, new_login: str): ...

    async def set_password(self, user_id: UUID, password_hash: str): ...

    async def increment_token_version(self, user_id: UUID) -> int: ...
