input {
  beats {
    port => 5044
  }
}

filter {
  # docker json log: полезное чаще всего в [message]
  if [message] {
    mutate { rename => { "message" => "log_message" } }
  }

  # имя сервиса: container.name
  if [docker][container][name] {
    mutate { add_field => { "service_name" => "%{[docker][container][name]}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
}
