[pytest]
minversion = 8.0
testpaths = tests
addopts = -q
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

filterwarnings =
    ignore:The configuration option "asyncio_default_fixture_loop_scope" is unset:pytest.PytestDeprecationWarning
    ignore:'.*asyncio\.get_event_loop_policy.*' is deprecated:DeprecationWarning
    ignore:'.*asyncio\.set_event_loop_policy.*' is deprecated:DeprecationWarning
    ignore:'.*asyncio\.iscoroutinefunction.*' is deprecated:DeprecationWarning
